Repository 5oreo5/ContactApp, pull requests merged in 2023-09, with the labels that each got.

#2 [FEAT] : ⚙️addContactDial.xml 추가
  .idea/deploymentTargetDropDown.xml
  .idea/misc.xml
  app/build.gradle.kts
  app/src/main/java/com/android/contectapp/addContactDialogFragment.kt
  app/src/main/res/drawable/addcontacts_iv_house.png
  app/src/main/res/layout/fragment_add_contact_dialog.xml
  build.gradle.kts
Labels: enhancement

#3 [FEAT] : ⚙️
  app/build.gradle.kts
  app/src/main/res/drawable/circleshape.xml
  app/src/main/res/layout/fragment_detail_contact.xml
  app/src/main/res/layout/fragment_my_page.xml
Labels: enhancement, UI

#6 수정하였습니다.conflict 해결
  app/build.gradle.kts
  app/src/main/java/com/android/contectapp/MainActivity.kt
  app/src/main/java/com/android/contectapp/MainAdapter.kt
  app/src/main/res/drawable/recycleview_iv_ellipse.png
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_recyclerview_item_list.xml
  app/src/main/res/values/themes.xml
Labels: enhancement

#8 [FEAT] : ⚙️add.xml 수정
  .idea/.name
  app/src/main/java/com/android/contectapp/addContactDialogFragment.kt
  app/src/main/res/layout/fragment_add_contact_dialog.xml
Labels: enhancement

#10 detailF and mypageF update
  .idea/misc.xml
  app/build.gradle.kts
  app/src/main/java/com/android/contectapp/DetailContactFragment.kt
  app/src/main/java/com/android/contectapp/MyPageFragment.kt
  app/src/main/res/layout/fragment_detail_contact.xml
  app/src/main/res/layout/fragment_my_page.xml
  build.gradle.kts
Labels: enhancement, UI

#11 [FEAT] : ⚙️ mainActivity viewPager로 각 페이지 연결 성공
  app/src/main/java/com/android/contectapp/MainActivity.kt
  app/src/main/res/color/menu_selected.xml
  app/src/main/res/drawable/tab_iv_contacts.png
  app/src/main/res/drawable/tab_iv_detailpage.png
  app/src/main/res/drawable/tab_iv_mypage.png
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/values/themes.xml
Labels: enhancement

#12 리사이클 뷰 어댑터 추가
  app/build.gradle.kts
  app/src/main/java/com/android/contectapp/Item.kt
  app/src/main/java/com/android/contectapp/recyclerviewAdapter.kt
  app/src/main/java/com/android/contectapp/recyclerview_item_list.kt
  app/src/main/res/layout/activity_recyclerview_item_list.xml
Labels: enhancement

#13 [FEAT] : ⚙️ contactlist_add_btn 추가
  app/build.gradle.kts
  app/src/main/res/drawable/contactlist_add_btn.png
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_contact_list.xml
  app/src/main/res/values/themes.xml
Labels: enhancement

#14 어댑터 연결
  .idea/.name
  app/src/main/java/com/android/contectapp/ContactListFragment.kt
  app/src/main/java/com/android/contectapp/Item.kt
  app/src/main/java/com/android/contectapp/recyclerviewAdapter.kt
  app/src/main/java/com/android/contectapp/recyclerview_item_list.kt
  app/src/main/res/layout/activity_recyclerview_item_list.xml
Labels: enhancement

#17 Add
  .idea/shelf/Uncommitted_changes_before_Checkout_at_2023_09_05_11_28_AM_[Changes]/shelved.patch
  .idea/shelf/Uncommitted_changes_before_Checkout_at_2023_09_05_11_28_AM_[Changes]1/shelved.patch
  app/src/main/java/com/android/contectapp/ContactListFragment.kt
  app/src/main/java/com/android/contectapp/Item.kt
  app/src/main/java/com/android/contectapp/addContactDialogFragment.kt
  app/src/main/java/com/android/contectapp/recyclerviewAdapter.kt
  app/src/main/java/com/android/contectapp/recyclerview_item_list.kt
  app/src/main/res/drawable/addcontacts_iv_alarm.png
  app/src/main/res/layout/activity_recyclerview_item_list.xml
  app/src/main/res/layout/fragment_add_contact_dialog.xml
Labels: enhancement

#18 RV 연결 및 data class, dummy data 수정
  .idea/deploymentTargetDropDown.xml
  app/build.gradle.kts
  app/src/main/java/com/android/contectapp/ContactListFragment.kt
  app/src/main/java/com/android/contectapp/DetailContactFragment.kt
  app/src/main/java/com/android/contectapp/Item.kt
  app/src/main/java/com/android/contectapp/recyclerviewAdapter.kt
  app/src/main/java/com/android/contectapp/recyclerview_item_list.kt
  app/src/main/res/layout/activity_recyclerview_item_list.xml
  build.gradle.kts
Labels: enhancement

#19 Feature/main activity2
  .idea/misc.xml
  .idea/shelf/Uncommitted_changes_before_Checkout_at_2023-09-05__8_50__Changes_.xml
  .idea/shelf/Uncommitted_changes_before_Checkout_at_2023-09-05__8_53__Changes_.xml
  .idea/shelf/Uncommitted_changes_before_Checkout_at_2023-09-05_오후_8_50_[Changes]/shelved.patch
  .idea/shelf/Uncommitted_changes_before_Checkout_at_2023-09-05_오후_8_53_[Changes]/shelved.patch
  .idea/shelf/Uncommitted_changes_before_Checkout_at_2023-09-05_오후_8_53_[Changes]1/shelved.patch
  app/build.gradle.kts
Labels: enhancement

#21 adapter image add
  app/src/main/java/com/android/contectapp/recyclerviewAdapter.kt
Labels: duplicate

#22 UI updates
  app/src/main/res/layout/activity_recyclerview_item_list.xml
Labels: UI

#24 [FEAT] : textwatcher/dialog 사이즈 / contactList버튼과 연결2
  app/src/main/java/com/android/contectapp/AddContactDialogFragment.kt
Labels: enhancement

#27 Updates All
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/android/contectapp/Adapter.kt
  app/src/main/java/com/android/contectapp/AddContactDialogFragment.kt
  app/src/main/java/com/android/contectapp/AltertReceiver.kt
  app/src/main/java/com/android/contectapp/ContactListFragment.kt
  app/src/main/java/com/android/contectapp/DetailContactFragment.kt
  app/src/main/java/com/android/contectapp/Item.kt
  app/src/main/java/com/android/contectapp/MainActivity.kt
  app/src/main/java/com/android/contectapp/MainAdapter.kt
  app/src/main/java/com/android/contectapp/Notification.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_add_contact_dialog.xml
Labels: bug, duplicate, enhancement

#30 [FEAT] : ⚙️xml 수정, 유효성 수정
  .idea/deploymentTargetDropDown.xml
  app/build.gradle.kts
  app/src/main/java/com/android/contectapp/Adapter.kt
  app/src/main/java/com/android/contectapp/AddContactDialogFragment.kt
  app/src/main/java/com/android/contectapp/ContactListFragment.kt
  app/src/main/java/com/android/contectapp/Item.kt
  app/src/main/java/com/android/contectapp/NotificationHelper.kt
  app/src/main/res/drawable/addcontacts_iv_add.png
  app/src/main/res/drawable/addcontacts_iv_person.png
  app/src/main/res/drawable/circle_background.xml
  app/src/main/res/drawable/circle_stroke.xml
  app/src/main/res/layout/fragment_add_contact_dialog.xml
Labels: enhancement

#32 Feature/swipecall, gridview(재원님)
  app/src/main/java/com/android/contectapp/Adapter.kt
  app/src/main/java/com/android/contectapp/AddContactDialogFragment.kt
  app/src/main/java/com/android/contectapp/CallHelper.kt
  app/src/main/java/com/android/contectapp/ContactListFragment.kt
  app/src/main/java/com/android/contectapp/Item.kt
  app/src/main/java/com/android/contectapp/MainActivity.kt
  app/src/main/java/com/android/contectapp/NotificationHelper.kt
  app/src/main/res/drawable/detail_iv_12.jpg
  app/src/main/res/layout/activity_girdview_item_list.xml
  app/src/main/res/layout/activity_recyclerview_item_list.xml
  app/src/main/res/values/strings.xml
Labels: bug, enhancement

#33 Feature/add 버그 수정!
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/android/contectapp/Adapter.kt
  app/src/main/java/com/android/contectapp/AddContactDialogFragment.kt
  app/src/main/java/com/android/contectapp/ContactListFragment.kt
  app/src/main/java/com/android/contectapp/Item.kt
  app/src/main/res/layout/activity_girdview_item_list.xml
  app/src/main/res/layout/activity_recyclerview_item_list.xml
Labels: bug

#34 [BUG_FIX] : 🐛 버그 수정! / 연락처 추가 시 ContactListFragment에 반영
  app/src/main/java/com/android/contectapp/AddContactDialogFragment.kt
  app/src/main/java/com/android/contectapp/ContactListFragment.kt
  app/src/main/java/com/android/contectapp/Item.kt
  app/src/main/res/layout/fragment_add_contact_dialog.xml
Labels: bug

#35 [BUG_FIX] : 🐛 버그 수정! / 유효성검사, 데이터 추가 수정
  app/src/main/java/com/android/contectapp/Adapter.kt
  app/src/main/java/com/android/contectapp/AddContactDialogFragment.kt
  app/src/main/java/com/android/contectapp/CallHelper.kt
  app/src/main/java/com/android/contectapp/ContactListFragment.kt
  app/src/main/java/com/android/contectapp/Item.kt
  app/src/main/res/layout/fragment_add_contact_dialog.xml
Labels: bug

#36 [BUG_FIX] : 🐛 버그 수정! / 데이터 추가 수정, 지현님 이미지 교체 추가
  app/src/main/java/com/android/contectapp/Adapter.kt
  app/src/main/java/com/android/contectapp/AddContactDialogFragment.kt
  app/src/main/java/com/android/contectapp/CallHelper.kt
  app/src/main/java/com/android/contectapp/Contact.kt
  app/src/main/java/com/android/contectapp/ContactListFragment.kt
  app/src/main/java/com/android/contectapp/DetailContactFragment.kt
  app/src/main/java/com/android/contectapp/MainActivity.kt
  app/src/main/java/com/android/contectapp/MyPageFragment.kt
  app/src/main/res/layout/fragment_add_contact_dialog.xml
Labels: bug

#38 [LITTLE_FIX] : 🔧 마이페이지 갤러리 접근 권한 수정 / 앱 이름 수정(슬연생)
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/android/contectapp/ContactListFragment.kt
  app/src/main/java/com/android/contectapp/DetailContactFragment.kt
  app/src/main/java/com/android/contectapp/MyPageFragment.kt
  app/src/main/res/values/strings.xml
Labels: bug

#39 [COMPLETION] : 🎉
  app/src/main/java/com/android/contectapp/AddContactDialogFragment.kt
  app/src/main/java/com/android/contectapp/ContactListFragment.kt
  app/src/main/java/com/android/contectapp/MainActivity.kt
Labels: enhancement
